development:
  adapter: postgresql
  database: feed_bucket_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: feed_bucket_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: feed_bucket_production
  pool: 5
  timeout: 5000
